package com.bastion.app.ui.theme

import androidx.compose.ui.graphics.Color

// Stitch Design System Colors — dark theme tokens
val StitchBackground = Color(0xFF0F1417)
val StitchSurface = Color(0xFF0F1417)
val StitchSurfaceDim = Color(0xFF0F1417)
val StitchSurfaceBright = Color(0xFF353A3D)
val StitchSurfaceContainerLowest = Color(0xFF0A0F12)
val StitchSurfaceContainerLow = Color(0xFF171C1F)
val StitchSurfaceContainer = Color(0xFF1B2023)
val StitchSurfaceContainerHigh = Color(0xFF262B2E)
val StitchSurfaceContainerHighest = Color(0xFF303539)
val StitchSurfaceVariant = Color(0xFF303539)
val StitchOnSurface = Color(0xFFDFE3E7)
val StitchOnSurfaceVariant = Color(0xFFBDC8D0)
val StitchPrimary = Color(0xFF9ADBFF)
val StitchOnPrimary = Color(0xFF003548)
val StitchPrimaryContainer = Color(0xFF4FC3F7)
val StitchOnPrimaryContainer = Color(0xFF004E69)
val StitchSecondary = Color(0xFF45FEC9)
val StitchOnSecondary = Color(0xFF003829)
val StitchSecondaryContainer = Color(0xFF00E1AE)
val StitchOnSecondaryContainer = Color(0xFF005E47)
val StitchTertiary = Color(0xFFFFC893)
val StitchTertiaryContainer = Color(0xFFFAA443)
val StitchOutline = Color(0xFF889299)
val StitchOutlineVariant = Color(0xFF3E484F)
val StitchError = Color(0xFFFFB4AB)
val StitchOnError = Color(0xFF690005)
val StitchErrorContainer = Color(0xFF93000A)
val StitchOnErrorContainer = Color(0xFFFFDAD6)

// Light theme tokens (inverse of dark)
val StitchLightBackground = Color(0xFFF8F9FA)
val StitchLightSurface = Color(0xFFF8F9FA)
val StitchLightSurfaceDim = Color(0xFFE0E3E7)
val StitchLightSurfaceBright = Color(0xFFF8F9FA)
val StitchLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val StitchLightSurfaceContainerLow = Color(0xFFF2F3F5)
val StitchLightSurfaceContainer = Color(0xFFECEEF0)
val StitchLightSurfaceContainerHigh = Color(0xFFE6E8EB)
val StitchLightSurfaceContainerHighest = Color(0xFFD0D3D7)
val StitchLightSurfaceVariant = Color(0xFFD0D3D7)
val StitchLightOnSurface = Color(0xFF1C2023)
val StitchLightOnSurfaceVariant = Color(0xFF495157)
val StitchLightPrimary = Color(0xFF006688)
val StitchLightOnPrimary = Color(0xFFFFFFFF)
val StitchLightPrimaryContainer = Color(0xFFC2E8FF)
val StitchLightOnPrimaryContainer = Color(0xFF001E2B)
val StitchLightSecondary = Color(0xFF006847)
val StitchLightOnSecondary = Color(0xFFFFFFFF)
val StitchLightSecondaryContainer = Color(0xFF45FEC9)
val StitchLightOnSecondaryContainer = Color(0xFF002117)
val StitchLightTertiary = Color(0xFF7D4D00)
val StitchLightTertiaryContainer = Color(0xFFFFDCBD)
val StitchLightOutline = Color(0xFF737C82)
val StitchLightOutlineVariant = Color(0xFFC1C7CD)
val StitchLightError = Color(0xFFBA1A1A)
val StitchLightOnError = Color(0xFFFFFFFF)
val StitchLightErrorContainer = Color(0xFFFFDAD6)
val StitchLightOnErrorContainer = Color(0xFF410002)

// Terminal
val TerminalBg = Color(0xFF0F1417)
val TerminalFg = Color(0xFFDFE3E7)
