package com.bastion.app.ui.theme

import androidx.compose.ui.graphics.Color

// Stitch Design System Colors — dark theme tokens
val StitchBackground = Color(0xFF0F1417)
val StitchSurface = Color(0xFF0F1417)
val StitchSurfaceDim = Color(0xFF0F1417)
val StitchSurfaceBright = Color(0xFF353A3D)
val StitchSurfaceContainerLowest = Color(0xFF0A0F12)
val StitchSurfaceContainerLow = Color(0xFF171C1F)
val StitchSurfaceContainer = Color(0xFF1B2023)
val StitchSurfaceContainerHigh = Color(0xFF262B2E)
val StitchSurfaceContainerHighest = Color(0xFF303539)
val StitchSurfaceVariant = Color(0xFF303539)
val StitchOnSurface = Color(0xFFDFE3E7)
val StitchOnSurfaceVariant = Color(0xFFBDC8D0)
val StitchPrimary = Color(0xFF9ADBFF)
val StitchOnPrimary = Color(0xFF003548)
val StitchPrimaryContainer = Color(0xFF4FC3F7)
val StitchOnPrimaryContainer = Color(0xFF004E69)
val StitchSecondary = Color(0xFF45FEC9)
val StitchOnSecondary = Color(0xFF003829)
val StitchSecondaryContainer = Color(0xFF00E1AE)
val StitchOnSecondaryContainer = Color(0xFF005E47)
val StitchTertiary = Color(0xFFFFC893)
val StitchTertiaryContainer = Color(0xFFFAA443)
val StitchOutline = Color(0xFF889299)
val StitchOutlineVariant = Color(0xFF3E484F)
val StitchError = Color(0xFFFFB4AB)
val StitchOnError = Color(0xFF690005)
val StitchErrorContainer = Color(0xFF93000A)
val StitchOnErrorContainer = Color(0xFFFFDAD6)

// Light theme tokens (inverse of dark)
val StitchLightBackground = Color(0xFFF8F9FA)
val StitchLightSurface = Color(0xFFF8F9FA)
val StitchLightSurfaceDim = Color(0xFFE0E3E7)
val StitchLightSurfaceBright = Color(0xFFF8F9FA)
val StitchLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val StitchLightSurfaceContainerLow = Color(0xFFF2F3F5)
val StitchLightSurfaceContainer = Color(0xFFECEEF0)
val StitchLightSurfaceContainerHigh = Color(0xFFE6E8EB)
val StitchLightSurfaceContainerHighest = Color(0xFFD0D3D7)
val StitchLightSurfaceVariant = Color(0xFFD0D3D7)
val StitchLightOnSurface = Color(0xFF1C2023)
val StitchLightOnSurfaceVariant = Color(0xFF495157)
val StitchLightPrimary = Color(0xFF006688)
val StitchLightOnPrimary = Color(0xFFFFFFFF)
val StitchLightPrimaryContainer = Color(0xFFC2E8FF)
val StitchLightOnPrimaryContainer = Color(0xFF001E2B)
val StitchLightSecondary = Color(0xFF006847)
val StitchLightOnSecondary = Color(0xFFFFFFFF)
val StitchLightSecondaryContainer = Color(0xFF45FEC9)
val StitchLightOnSecondaryContainer = Color(0xFF002117)
val StitchLightTertiary = Color(0xFF7D4D00)
val StitchLightTertiaryContainer = Color(0xFFFFDCBD)
val StitchLightOutline = Color(0xFF737C82)
val StitchLightOutlineVariant = Color(0xFFC1C7CD)
val StitchLightError = Color(0xFFBA1A1A)
val StitchLightOnError = Color(0xFFFFFFFF)
val StitchLightErrorContainer = Color(0xFFFFDAD6)
val StitchLightOnErrorContainer = Color(0xFF410002)

// Monokai theme tokens (code-editor inspired dark scheme)
val MonokaiBackground = Color(0xFF272822)
val MonokaiSurface = Color(0xFF272822)
val MonokaiSurfaceDim = Color(0xFF1E1F1A)
val MonokaiSurfaceBright = Color(0xFF3E3F37)
val MonokaiSurfaceContainerLowest = Color(0xFF1A1B16)
val MonokaiSurfaceContainerLow = Color(0xFF2D2E25)
val MonokaiSurfaceContainer = Color(0xFF33342B)
val MonokaiSurfaceContainerHigh = Color(0xFF3D3E33)
val MonokaiSurfaceContainerHighest = Color(0xFF494A3E)
val MonokaiSurfaceVariant = Color(0xFF3D3E33)
val MonokaiOnSurface = Color(0xFFF8F8F2)
val MonokaiOnSurfaceVariant = Color(0xFFA0A090)
val MonokaiPrimary = Color(0xFFA6E22E)
val MonokaiOnPrimary = Color(0xFF1A1F0A)
val MonokaiPrimaryContainer = Color(0xFF6B9E1E)
val MonokaiOnPrimaryContainer = Color(0xFF0D1400)
val MonokaiSecondary = Color(0xFFFD971F)
val MonokaiOnSecondary = Color(0xFF2D1C00)
val MonokaiSecondaryContainer = Color(0xFFC47800)
val MonokaiOnSecondaryContainer = Color(0xFF1A0F00)
val MonokaiTertiary = Color(0xFF66D9EF)
val MonokaiTertiaryContainer = Color(0xFF1D9DB5)
val MonokaiOutline = Color(0xFF75715E)
val MonokaiOutlineVariant = Color(0xFF49483E)
val MonokaiError = Color(0xFFF92672)
val MonokaiOnError = Color(0xFF3E0016)
val MonokaiErrorContainer = Color(0xFFB0004A)
val MonokaiOnErrorContainer = Color(0xFFFFD1DA)

// Terminal
val TerminalBg = Color(0xFF0F1417)
val TerminalFg = Color(0xFFDFE3E7)
