package com.bastion.app.ui.theme

import androidx.compose.ui.graphics.Color

// Stitch Design System "Terminal Core" — dark mode tokens
// Fuente: https://stitch.googleapis.com/mcp project 2946918035035581471
val StitchBackground = Color(0xFF0c160a)
val StitchSurface = Color(0xFF0c160a)
val StitchSurfaceDim = Color(0xFF0c160a)
val StitchSurfaceBright = Color(0xFF313c2e)
val StitchSurfaceContainerLowest = Color(0xFF071106)
val StitchSurfaceContainerLow = Color(0xFF141e12)
val StitchSurfaceContainer = Color(0xFF182216)
val StitchSurfaceContainerHigh = Color(0xFF222d20)
val StitchSurfaceContainerHighest = Color(0xFF2d382a)
val StitchSurfaceVariant = Color(0xFF2d382a)
val StitchOnSurface = Color(0xFFdae6d2)
val StitchOnSurfaceVariant = Color(0xFFb9ccb2)
val StitchInverseSurface = Color(0xFFdae6d2)
val StitchInverseOnSurface = Color(0xFF283326)
val StitchPrimary = Color(0xFFebffe2)
val StitchOnPrimary = Color(0xFF003907)
val StitchPrimaryContainer = Color(0xFF00ff41)
val StitchOnPrimaryContainer = Color(0xFF007117)
val StitchInversePrimary = Color(0xFF006e16)
val StitchPrimaryFixed = Color(0xFF72ff70)
val StitchPrimaryFixedDim = Color(0xFF00e639)
val StitchOnPrimaryFixed = Color(0xFF002203)
val StitchOnPrimaryFixedVariant = Color(0xFF00530e)
val StitchSecondary = Color(0xFFadc7ff)
val StitchOnSecondary = Color(0xFF002e68)
val StitchSecondaryContainer = Color(0xFF4a8eff)
val StitchOnSecondaryContainer = Color(0xFF00285b)
val StitchSecondaryFixed = Color(0xFFd8e2ff)
val StitchSecondaryFixedDim = Color(0xFFadc7ff)
val StitchOnSecondaryFixed = Color(0xFF001a41)
val StitchOnSecondaryFixedVariant = Color(0xFF004493)
val StitchTertiary = Color(0xFFfff8f4)
val StitchOnTertiary = Color(0xFF442b10)
val StitchTertiaryContainer = Color(0xFFffd5ae)
val StitchOnTertiaryContainer = Color(0xFF7a5b3c)
val StitchTertiaryFixed = Color(0xFFffdcbd)
val StitchTertiaryFixedDim = Color(0xFFe7bf99)
val StitchOnTertiaryFixed = Color(0xFF2c1701)
val StitchOnTertiaryFixedVariant = Color(0xFF5d4124)
val StitchOutline = Color(0xFF84967e)
val StitchOutlineVariant = Color(0xFF3b4b37)
val StitchError = Color(0xFFffb4ab)
val StitchOnError = Color(0xFF690005)
val StitchErrorContainer = Color(0xFF93000a)
val StitchOnErrorContainer = Color(0xFFffdad6)
val StitchSurfaceTint = Color(0xFF00e639)

// Light theme tokens (placeholder — no diseñado aún en Stitch)
val StitchLightBackground = Color(0xFFF8F9FA)
val StitchLightSurface = Color(0xFFF8F9FA)
val StitchLightSurfaceDim = Color(0xFFE0E3E7)
val StitchLightSurfaceBright = Color(0xFFF8F9FA)
val StitchLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val StitchLightSurfaceContainerLow = Color(0xFFF2F3F5)
val StitchLightSurfaceContainer = Color(0xFFECEEF0)
val StitchLightSurfaceContainerHigh = Color(0xFFE6E8EB)
val StitchLightSurfaceContainerHighest = Color(0xFFD0D3D7)
val StitchLightSurfaceVariant = Color(0xFFD0D3D7)
val StitchLightOnSurface = Color(0xFF1C2023)
val StitchLightOnSurfaceVariant = Color(0xFF495157)
val StitchLightPrimary = Color(0xFF006e16)
val StitchLightOnPrimary = Color(0xFFFFFFFF)
val StitchLightPrimaryContainer = Color(0xFF72ff70)
val StitchLightOnPrimaryContainer = Color(0xFF002203)
val StitchLightSecondary = Color(0xFF004493)
val StitchLightOnSecondary = Color(0xFFFFFFFF)
val StitchLightSecondaryContainer = Color(0xFFd8e2ff)
val StitchLightOnSecondaryContainer = Color(0xFF001a41)
val StitchLightTertiary = Color(0xFF5d4124)
val StitchLightTertiaryContainer = Color(0xFFffdcbd)
val StitchLightOutline = Color(0xFF737C82)
val StitchLightOutlineVariant = Color(0xFFC1C7CD)
val StitchLightError = Color(0xFFBA1A1A)
val StitchLightOnError = Color(0xFFFFFFFF)
val StitchLightErrorContainer = Color(0xFFFFDAD6)
val StitchLightOnErrorContainer = Color(0xFF410002)

// Monokai theme (used in SettingsScreen + Theme.kt)
val MonokaiBackground = Color(0xFF272822)
val MonokaiSurface = Color(0xFF272822)
val MonokaiSurfaceVariant = Color(0xFF3E3D32)
val MonokaiOnSurface = Color(0xFFF8F8F2)
val MonokaiOnSurfaceVariant = Color(0xFFA59F85)
val MonokaiPrimary = Color(0xFF66D9EF)
val MonokaiOnPrimary = Color(0xFF003548)
val MonokaiPrimaryContainer = Color(0xFF007C9C)
val MonokaiOnPrimaryContainer = Color(0xFFB3F0FF)
val MonokaiSecondary = Color(0xFFA6E22E)
val MonokaiOnSecondary = Color(0xFF1E3A00)
val MonokaiSecondaryContainer = Color(0xFF4B7A00)
val MonokaiOnSecondaryContainer = Color(0xFFD4FFA8)
val MonokaiTertiary = Color(0xFFFD971F)
val MonokaiTertiaryContainer = Color(0xFFB05E00)
val MonokaiOutline = Color(0xFF75715E)
val MonokaiOutlineVariant = Color(0xFF49483E)
val MonokaiError = Color(0xFFF92672)
val MonokaiOnError = Color(0xFF4A0019)
val MonokaiErrorContainer = Color(0xFF7F0036)
val MonokaiOnErrorContainer = Color(0xFFFFB0C8)

// Terminal
val TerminalBg = StitchBackground
val TerminalFg = StitchOnSurface
